name: Compilar APK Android

on:
  push:
    branches:
      - Dev.-Alejandro
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Compilar con Buildozer
        uses: digreatbrian/buildozer-action@v2
        with:
          python-version: 3.10
          buildozer-cmd: buildozer -v android debug

      - name: Subir APK final
        uses: actions/upload-artifact@v4
        with:
          name: LabubuCalc-APK
          path: ./bin/*.apk
